In [1]:
%reload_ext autoreload
# %load_ext fireducks.pandas # linux only for now

In [2]:
from kret_studies import *
from kret_studies.notebook_imports import *

In [3]:
A = np.array([[1, -2], [0, 1], [1, 0]])
sigma = np.array([[np.sqrt(6), 1], [0, 1], [0, 0]])

In [4]:
sigma

array([[2.44948974, 1.        ],
       [0.        , 1.        ],
       [0.        , 0.        ]])

In [5]:
sigma_psuedo = np.linalg.pinv(sigma)

In [6]:
sigma_psuedo.round(2)

array([[ 0.41, -0.41,  0.  ],
       [ 0.  ,  1.  ,  0.  ]])

In [7]:
(sigma_psuedo @ sigma).round(2)

array([[1., 0.],
       [0., 1.]])

In [8]:
(sigma @ sigma_psuedo).round(2)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])

In [11]:
A_psuedo = uks_np.solve_psuedo_inverse(A)

In [ ]:
(A_psuedo @ A).round(2)

array([[ 1., -0.],
       [ 0.,  1.]])

In [18]:
A_psuedo.round(2)

array([[ 0.17,  0.33,  0.83],
       [-0.33,  0.33,  0.33]])

In [19]:
sigma_2 = np.array([[3, 0], [0, 5], [0, 0], [0, 0]])

In [ ]:
sigma_2_t_sigma = sigma_2.T @ sigma_2
sigma_2_t_sigma

array([[ 9,  0],
       [ 0, 25]])

In [22]:
np.linalg.pinv(sigma_2)

array([[0.33333333, 0.        , 0.        , 0.        ],
       [0.        , 0.2       , 0.        , 0.        ]])

In [25]:
sigma_2_psuedo = np.linalg.inv(sigma_2_t_sigma) @ sigma_2.T

In [26]:
sigma_2_psuedo @ sigma_2

array([[1., 0.],
       [0., 1.]])

In [31]:
sigma_2 = np.array([[4, 0], [0, 25]])
sigma_2

array([[ 4,  0],
       [ 0, 25]])

In [33]:
sigma_2_inv = np.linalg.inv(sigma_2)

In [34]:
sigma_2 @ sigma_2_inv

array([[1., 0.],
       [0., 1.]])